name: quick-cover
version: 0.1.0.0
github: "https://github.com/hgoldstein95/quick-cover"
license: MIT
author: "Harrison Goldstein"
maintainer: "hgo@seas.upenn.edu"
copyright: "2020 Harrison Goldstein"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/quickcover#readme>

dependencies:
  - base >= 4.7 && < 5
  - QuickCheck
  - mtl
  - containers
  - microtimer
  - deepseq
  - async
  - logict
  - MonadRandom
  - random
  - clock
  - universe
  - universe-base

library:
  source-dirs: src

executables:
  quickcover-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - quick-cover

tests:
  quickcover-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - quick-cover
